### PR TITLE
FIX-1893 Case insensitive comparison on server urls

### LINKED ISSUE #1893: Case insensitive matching on server urls
Ensure that whenever two server urls are compared, the comparison is case insensitive, to avoid potential problems due to urls being entered differently in multiple places.

Affects among others:
Witsml.IWitsmlClient.GetServerHostname()
Api.ServerCredentials.Host
Api.Server.Url
Frontend.Server.url

### PR DESCRIPTION
**Pull request by jaroslavbliznak**
[//]: # (Request Template Witsml Explorer)

[//]: # (Thank you for contributing to WITSML Explorer! Before submitting this PR, please fill in the following template.)

## Fixes

[//]: # (Write the GitHub issue number starting with #, or, for Equinor only, the Jira issue number starting with WE-)

This pull request fixes #1893 

## Description

[//]: # (Please include a written summary of the changes and which issue is fixed. List any dependencies that are required for this change._)

## Type of change

[//]: # (Mark any of the types of change that apply.)

* [ ] Bugfix
* [ ] New feature (non-breaking change which adds functionality)
* [ ] Enhancement of existing functionality
* [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
* [ ] This change requires a documentation update

## Impacted Areas in Application

[//]: # (List general components of the application that this PR will affect)

* [ ] Frontend
* [ ] API
* [ ] WITSML
* [ ] Other (please describe)

## Checklist:

[//]: # (Please tick all the boxes or remove the ones that aren't needed and explain why)

*Communication*
* [ ] I have made corresponding changes to the documentation
* [ ] PR affects application security

*Code quality*
* [ ] I have self-reviewed my code
* [ ] No new warnings are generated

*Test coverage*
* [ ] New code is covered by passing tests

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

File: Src/Witsml/Extensions/StringExtensions.cs [hunk 1]
```diff
@@ -13,5 +14,25 @@ public static string NullIfEmpty(this string value)
...
             return string.IsNullOrEmpty(value) ? null : value;
         }
+        
+        /// <summary>
+        /// Determines whether two specified string objects have the same value.
+        /// </summary>
+        /// The first string to compare.
+        /// The second string to compare.
+        /// <returns>True if the value of the <paramref name="firstValue" /> parameter is equal to the value of the <paramref name="secondValue" />, otherwise return false.</returns>
+        public static bool EqualsIgnoreCase(this string firstValue, string secondValue)
```
Comment (janburak) [inline Src/Witsml/Extensions/StringExtensions.cs]: Would it be better to make this an extensions of `Uri` instead of `string` to avoid calling `toString()` before every call of EqualsIgnoreCase?

Other than that this method seems to replicate `string.Equals(firstValue, secondValue, StringComparison.OrdinalIgnoreCase)` functionality.

Comment (jaroslavbliznak) [reply Src/Witsml/Extensions/StringExtensions.cs]: I fixed it again with == operator, because comparison is case sensitive  and includes more valid cases.

Comment (janburak) [reply Src/Witsml/Extensions/StringExtensions.cs]: The comparison is supposed to be not case sensitive, so the `==` operator cannot be used in this case.

Comment (jaroslavbliznak) [reply Src/Witsml/Extensions/StringExtensions.cs]: Sorry, I meant to say that == operator is case insensitive for Uri.

Comment (janburak) [reply Src/Witsml/Extensions/StringExtensions.cs]: The `==` operator is case sensitive for `Uri`.
image

Comment (jaroslavbliznak) [reply Src/Witsml/Extensions/StringExtensions.cs]: I tested these Uri "HTTPS://www.EXAMPLE.com/" or "HTTPS://WWW.example.com/" it is case-insensitive and everything else is case-sensitive. For example https://en.wikipedia.org/wiki/GIt is not found, but https://en.wikipedia.org/wiki/Git is correct.
If should it be case insensitive also after the slash in this case, so I will change it.

Comment (janburak) [reply Src/Witsml/Extensions/StringExtensions.cs]: Yes, it should be case insensitive after the slash. This was requested by Stian Steinsbø Lie due to disrepancies in how WITSML server URLs are entered across different systems interacting with WITSML servers. Thank you for clarifying.

Comment (jaroslavbliznak) [reply Src/Witsml/Extensions/StringExtensions.cs]: ok no problem, I will change it.

Comment (jaroslavbliznak) [reply Src/Witsml/Extensions/StringExtensions.cs]: Corrected.

**Review by janburak — DISMISSED** [review]
- [X] Read issue and PR
- [X] Pulled branch and manually tested
- [X] Verify that PR resolves issue
- [X] Reviewed the code

Please use topic branches on your fork for future PRs, rather than main, as specified in the [fork and pull request workflow](https://github.com/susam/gitpr#work-on-pull-request) which is our contributing process as specified in [CONTRIBUTING.MD](https://github.com/equinor/witsml-explorer/blob/main/CONTRIBUTING.md). This is to avoid including commits from other PRs in your PRs.
